version: '2'
services:
  apimrdbms:
    container_name: apim_apimrdbms
    build: 
        context: .
        dockerfile: apimdb.dfile
    ports:
     - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
  gateway:
    container_name: apim_gateway
    depends_on: 
      - apimrdbms
    build:
      context: .
      dockerfile: apim-gateway.dfile
    ports:
      - "9763:9763"
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
  km:
    container_name: apim_km
    depends_on: 
      - apimrdbms
    build:
      context: .
      dockerfile: apim-km.dfile
    ports:
      - "9764:9763"
      - "9444:9443"
  publisher:
    container_name: apim_publisher
    depends_on: 
      - apimrdbms
    build:
      context: .
      dockerfile: apim-publisher.dfile
    ports:
      - "9765:9763"
      - "9445:9443"
  store:
    container_name: apim_store
    depends_on: 
      - apimrdbms
    build:
      context: .
      dockerfile: apim-store.dfile
    ports:
      - "9766:9763"
      - "9446:9443"